services:
  service_a:
    environment:
      - APP_ENV=prod
    build:
      args:
        SERVICE_PATH: "service-input"
        SERVICE_PORT: "8080"
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  service_b:
    environment:
      - APP_ENV=prod
    build:
      args:
        
        SERVICE_PATH: "service-orchestrator"
        SERVICE_PORT: "8081"
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector

  zipkin:
    image: openzipkin/zipkin:3
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:0.128.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
